# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FirebaseEx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseUI', '~> 4.0'       # Pull in all Firebase UI features
pod 'TwitterCore', '<=2.8.0' # fixed

  # Pods for FirebaseEx

end
